drop index FLW_RU_BATCH_PART.FLW_IDX_BATCH_PART;

alter table FLW_RU_BATCH_PART
    drop CONSTRAINT FLW_FK_BATCH_PART_PARENT;

drop table if exists FLW_RU_BATCH_PART cascade;
drop table if exists FLW_RU_BATCH cascade;

drop index ACT_RU_ENTITYLINK.ACT_IDX_ENT_LNK_SCOPE;
drop index ACT_RU_ENTITYLINK.ACT_IDX_ENT_LNK_REF_SCOPE;
drop index ACT_RU_ENTITYLINK.ACT_IDX_ENT_LNK_ROOT_SCOPE;
drop index ACT_RU_ENTITYLINK.ACT_IDX_ENT_LNK_SCOPE_DEF;

drop table if exists ACT_RU_ENTITYLINK cascade;

drop index ACT_HI_ENTITYLINK.ACT_IDX_HI_ENT_LNK_SCOPE;
drop index ACT_HI_ENTITYLINK.ACT_IDX_HI_ENT_LNK_REF_SCOPE;
drop index ACT_HI_ENTITYLINK.ACT_IDX_HI_ENT_LNK_ROOT_SCOPE;
drop index ACT_HI_ENTITYLINK.ACT_IDX_HI_ENT_LNK_SCOPE_DEF;

drop table if exists ACT_HI_ENTITYLINK cascade;

drop index ACT_RU_EVENT_SUBSCR.ACT_IDX_EVENT_SUBSCR_CONFIG_;
drop index ACT_RU_EVENT_SUBSCR.ACT_IDX_EVENT_SUBSCR_EXEC_ID;
drop index ACT_RU_EVENT_SUBSCR.ACT_IDX_EVENT_SUBSCR_PROC_ID;
drop index ACT_RU_EVENT_SUBSCR.ACT_IDX_EVENT_SUBSCR_SCOPEREF_;

drop table if exists ACT_RU_EVENT_SUBSCR cascade;

drop index ACT_RU_IDENTITYLINK.ACT_IDX_IDENT_LNK_USER;
drop index ACT_RU_IDENTITYLINK.ACT_IDX_IDENT_LNK_GROUP;
drop index ACT_RU_IDENTITYLINK.ACT_IDX_IDENT_LNK_SCOPE;
drop index ACT_RU_IDENTITYLINK.ACT_IDX_IDENT_LNK_SUB_SCOPE;
drop index ACT_RU_IDENTITYLINK.ACT_IDX_IDENT_LNK_SCOPE_DEF;

drop table if exists ACT_RU_IDENTITYLINK cascade;

drop index ACT_HI_IDENTITYLINK.ACT_IDX_HI_IDENT_LNK_USER;
drop index ACT_HI_IDENTITYLINK.ACT_IDX_HI_IDENT_LNK_SCOPE;
drop index ACT_HI_IDENTITYLINK.ACT_IDX_HI_IDENT_LNK_SUB_SCOPE;
drop index ACT_HI_IDENTITYLINK.ACT_IDX_HI_IDENT_LNK_SCOPE_DEF;

drop table if exists ACT_HI_IDENTITYLINK cascade;

alter table ACT_RU_JOB
    drop CONSTRAINT ACT_FK_JOB_EXCEPTION;

alter table ACT_RU_JOB
    drop CONSTRAINT ACT_FK_JOB_CUSTOM_VALUES;

alter table ACT_RU_TIMER_JOB
    drop CONSTRAINT ACT_FK_TIMER_JOB_EXCEPTION;

alter table ACT_RU_TIMER_JOB
    drop CONSTRAINT ACT_FK_TIMER_JOB_CUSTOM_VALUES;

alter table ACT_RU_SUSPENDED_JOB
    drop CONSTRAINT ACT_FK_SUSPENDED_JOB_EXCEPTION;

alter table ACT_RU_SUSPENDED_JOB
    drop CONSTRAINT ACT_FK_SUSPENDED_JOB_CUSTOM_VALUES;

alter table ACT_RU_DEADLETTER_JOB
    drop CONSTRAINT ACT_FK_DEADLETTER_JOB_EXCEPTION;

alter table ACT_RU_DEADLETTER_JOB
    drop CONSTRAINT ACT_FK_DEADLETTER_JOB_CUSTOM_VALUES;

alter table ACT_RU_EXTERNAL_JOB
    drop CONSTRAINT ACT_FK_EXTERNAL_JOB_EXCEPTION;

alter table ACT_RU_EXTERNAL_JOB
    drop CONSTRAINT ACT_FK_EXTERNAL_JOB_CUSTOM_VALUES;

drop index ACT_RU_JOB.ACT_IDX_JOB_EXCEPTION_STACK_ID;
drop index ACT_RU_JOB.ACT_IDX_JOB_CUSTOM_VALUES_ID;
drop index ACT_RU_JOB.ACT_IDX_JOB_CORRELATION_ID;
drop index ACT_RU_JOB.ACT_IDX_JOB_SCOPE;
drop index ACT_RU_JOB.ACT_IDX_JOB_SUB_SCOPE;
drop index ACT_RU_JOB.ACT_IDX_JOB_SCOPE_DEF;

drop index ACT_RU_TIMER_JOB.ACT_IDX_TIMER_JOB_EXCEPTION_STACK_ID;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TIMER_JOB_CUSTOM_VALUES_ID;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TIMER_JOB_CORRELATION_ID;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TIMER_JOB_DUEDATE;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TJOB_SCOPE;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TJOB_SUB_SCOPE;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TJOB_SCOPE_DEF;

drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SUSPENDED_JOB_EXCEPTION_STACK_ID;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SUSPENDED_JOB_CUSTOM_VALUES_ID;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SUSPENDED_JOB_CORRELATION_ID;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SJOB_SCOPE;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SJOB_SUB_SCOPE;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SJOB_SCOPE_DEF;

drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DEADLETTER_JOB_EXCEPTION_STACK_ID;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DEADLETTER_JOB_CUSTOM_VALUES_ID;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DEADLETTER_JOB_CORRELATION_ID;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DJOB_SCOPE;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DJOB_SUB_SCOPE;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DJOB_SCOPE_DEF;

drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EXTERNAL_JOB_EXCEPTION_STACK_ID;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EXTERNAL_JOB_CUSTOM_VALUES_ID;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EXTERNAL_JOB_CORRELATION_ID;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EJOB_SCOPE;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EJOB_SUB_SCOPE;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EJOB_SCOPE_DEF;

drop table if exists ACT_RU_JOB cascade;
drop table if exists ACT_RU_TIMER_JOB cascade;
drop table if exists ACT_RU_SUSPENDED_JOB cascade;
drop table if exists ACT_RU_DEADLETTER_JOB cascade;
drop table if exists ACT_RU_HISTORY_JOB cascade;
drop table if exists ACT_RU_EXTERNAL_JOB cascade;

drop index ACT_RU_TASK.ACT_IDX_TASK_CREATE;
drop index ACT_RU_TASK.ACT_IDX_TASK_SCOPE;
drop index ACT_RU_TASK.ACT_IDX_TASK_SUB_SCOPE;
drop index ACT_RU_TASK.ACT_IDX_TASK_SCOPE_DEF;

drop table if exists ACT_RU_TASK cascade;

drop index ACT_HI_TSK_LOG.ACT_IDX_ACT_HI_TSK_LOG_TASK;

drop table if exists ACT_HI_TSK_LOG cascade;

drop index ACT_HI_TASKINST.ACT_IDX_HI_TASK_SCOPE;
drop index ACT_HI_TASKINST.ACT_IDX_HI_TASK_SUB_SCOPE;
drop index ACT_HI_TASKINST.ACT_IDX_HI_TASK_SCOPE_DEF;

drop table if exists ACT_HI_TASKINST cascade;

alter table ACT_RU_VARIABLE
    drop CONSTRAINT ACT_FK_VAR_BYTEARRAY;
    
drop index ACT_RU_VARIABLE.ACT_IDX_RU_VAR_SCOPE_ID_TYPE;
drop index ACT_RU_VARIABLE.ACT_IDX_RU_VAR_SUB_ID_TYPE;    

drop table if exists ACT_RU_VARIABLE cascade;

drop index ACT_HI_VARINST.ACT_IDX_HI_PROCVAR_NAME_TYPE;
drop index ACT_HI_VARINST.ACT_IDX_HI_VAR_SCOPE_ID_TYPE;
drop index ACT_HI_VARINST.ACT_IDX_HI_VAR_SUB_ID_TYPE;

drop table if exists ACT_HI_VARINST cascade;


drop table if exists ACT_GE_BYTEARRAY cascade;
drop table if exists ACT_GE_PROPERTY cascade;

