drop index ACT_HI_TASKINST.ACT_IDX_HI_TASK_SCOPE;
drop index ACT_HI_TASKINST.ACT_IDX_HI_TASK_SUB_SCOPE;
drop index ACT_HI_TASKINST.ACT_IDX_HI_TASK_SCOPE_DEF;

drop table if exists ACT_HI_TASKINST;
drop table if exists ACT_HI_TSK_LOG;