drop index ACT_RU_TASK.ACT_IDX_TASK_CREATE;
drop index ACT_RU_TASK.ACT_IDX_TASK_SCOPE;
drop index ACT_RU_TASK.ACT_IDX_TASK_SUB_SCOPE;
drop index ACT_RU_TASK.ACT_IDX_TASK_SCOPE_DEF;

drop table if exists ACT_RU_TASK cascade;