drop index ACT_RU_JOB.ACT_IDX_JOB_SCOPE;
drop index ACT_RU_JOB.ACT_IDX_JOB_SUB_SCOPE;
drop index ACT_RU_JOB.ACT_IDX_JOB_SCOPE_DEF;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TJOB_SCOPE;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TJOB_SUB_SCOPE;
drop index ACT_RU_TIMER_JOB.ACT_IDX_TJOB_SCOPE_DEF;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SJOB_SCOPE;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SJOB_SUB_SCOPE;
drop index ACT_RU_SUSPENDED_JOB.ACT_IDX_SJOB_SCOPE_DEF;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DJOB_SCOPE;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DJOB_SUB_SCOPE;
drop index ACT_RU_DEADLETTER_JOB.ACT_IDX_DJOB_SCOPE_DEF;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EJOB_SCOPE;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EJOB_SUB_SCOPE;
drop index ACT_RU_EXTERNAL_JOB.ACT_IDX_EJOB_SCOPE_DEF;

alter table ACT_RU_JOB
    drop CONSTRAINT ACT_FK_JOB_EXCEPTION;

alter table ACT_RU_JOB
    drop CONSTRAINT ACT_FK_JOB_CUSTOM_VALUES;

alter table ACT_RU_TIMER_JOB
    drop CONSTRAINT ACT_FK_TIMER_JOB_EXCEPTION;

alter table ACT_RU_TIMER_JOB
    drop CONSTRAINT ACT_FK_TIMER_JOB_CUSTOM_VALUES;

alter table ACT_RU_SUSPENDED_JOB
    drop CONSTRAINT ACT_FK_SUSPENDED_JOB_EXCEPTION;

alter table ACT_RU_SUSPENDED_JOB
    drop CONSTRAINT ACT_FK_SUSPENDED_JOB_CUSTOM_VALUES;

alter table ACT_RU_DEADLETTER_JOB
    drop CONSTRAINT ACT_FK_DEADLETTER_JOB_EXCEPTION;

alter table ACT_RU_DEADLETTER_JOB
    drop CONSTRAINT ACT_FK_DEADLETTER_JOB_CUSTOM_VALUES;

alter table ACT_RU_EXTERNAL_JOB
    drop CONSTRAINT ACT_FK_EXTERNAL_JOB_EXCEPTION;

alter table ACT_RU_EXTERNAL_JOB
    drop CONSTRAINT ACT_FK_EXTERNAL_JOB_CUSTOM_VALUES;

drop table if exists ACT_RU_JOB;
drop table if exists ACT_RU_TIMER_JOB;
drop table if exists ACT_RU_SUSPENDED_JOB;
drop table if exists ACT_RU_DEADLETTER_JOB;
drop table if exists ACT_RU_HISTORY_JOB;
drop table if exists ACT_RU_EXTERNAL_JOB;